BEGIN;

CREATE TABLE IF NOT EXISTS ingestion_locks (
  name VARCHAR(100) PRIMARY KEY,
  run_id UUID NOT NULL,
  locked_until TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
