import PDFDocument from 'pdfkit';
import { randomBytes } from 'node:crypto';
import { query } from './db.js';
import { BANK_PAYMENT_DETAILS, PLAN_PRICES_CENTS } from './payments.js';

export const VAT_RATE = 0.15;
export type BillingDocumentType = 'quote' | 'invoice';
const supplier = { legalName: 'NuMedia Direct Marketing (Pty) Ltd', tradingName: 'MarketDirect.co.za', vatNumber: '4310304052', address: '10 Falcon Lane, Sandton, Gauteng, 2191, South Africa', email: 'accounts@marketdirect.co.za' };
const money = (cents: number) => `R ${(cents / 100).toLocaleString('en-ZA', { minimumFractionDigits: 2 })}`;
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] || c));
const documentNumber = (type: BillingDocumentType) => `MD-${type === 'quote' ? 'QT' : 'INV'}-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${randomBytes(3).toString('hex').toUpperCase()}`;
const totals = (amountCents: number) => { const vatCents = Math.round(amountCents * VAT_RATE); return { subtotalCents: amountCents, taxableTotalCents: amountCents, vatCents, totalCents: amountCents + vatCents }; };

export function planLine(plan: string, cycle: string) { const key = plan === 'agency' ? 'agency' : 'pro'; const billing = cycle === 'annual' ? 'annual' : 'monthly'; return { description: `EstateWatch ${key === 'agency' ? 'Agency / Firm' : 'Pro Solo'} subscription (${billing})`, quantity: 1, unitPriceCents: PLAN_PRICES_CENTS[key][billing] }; }

export async function createBillingDocument(input: { userId: string; type: BillingDocumentType; plan: string; cycle: string; customer: Record<string, unknown>; paymentId?: string | null; status?: string }) {
  const line = planLine(input.plan, input.cycle); const sums = totals(line.unitPriceCents); const validUntil = input.type === 'quote' ? new Date(Date.now() + 14 * 86400000) : null;
  const result = await query(`INSERT INTO billing_documents(user_id,type,status,document_number,share_token,plan_key,billing_cycle,customer_snapshot,supplier_snapshot,banking_snapshot,line_items,subtotal_cents,taxable_total_cents,vat_cents,total_cents,issue_date,validity_date,payment_id,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12,$13,$14,$15,NOW(),$16,$17,$18) RETURNING *`, [input.userId, input.type, input.status || 'sent', documentNumber(input.type), randomBytes(24).toString('base64url'), input.plan, input.cycle, JSON.stringify(input.customer), JSON.stringify(supplier), JSON.stringify(BANK_PAYMENT_DETAILS), JSON.stringify([{ ...line, lineTotalCents: line.unitPriceCents }]), sums.subtotalCents, sums.taxableTotalCents, sums.vatCents, sums.totalCents, validUntil, input.paymentId || null, input.type === 'quote' ? 'Payment due before activation. Quote valid for 14 days.' : 'Payment received. Thank you for choosing EstateWatch.']);
  return result.rows[0];
}

export async function createInvoiceForPayment(payment: any) {
  const existing = await query(`SELECT * FROM billing_documents WHERE payment_id=$1 AND type='invoice'`, [payment.id]); if (existing.rows[0]) return existing.rows[0];
  const user = (await query(`SELECT display_name,email,phone_number,company_name FROM user_profiles WHERE auth_subject=$1`, [payment.user_id])).rows[0] || {};
  return createBillingDocument({ userId: payment.user_id, type: 'invoice', plan: payment.plan_key, cycle: payment.billing_cycle, paymentId: payment.id, status: 'paid', customer: { name: user.display_name || user.email, companyName: user.company_name || '', email: user.email || '', phone: user.phone_number || '', vatNumber: '' } });
}

export function renderBillingPdf(document: any) { return new Promise<Buffer>((resolve, reject) => { const pdf: any = new PDFDocument({ size: 'A4', margin: 42, info: { Title: `${document.type === 'invoice' ? 'Invoice' : 'Quote'} ${document.document_number}` } }); const chunks: Buffer[] = []; pdf.on('data', (chunk: Buffer) => chunks.push(chunk)); pdf.on('end', () => resolve(Buffer.concat(chunks))); pdf.on('error', reject); const customer = document.customer_snapshot || {}; const line = (document.line_items || [])[0] || {}; const invoice = document.type === 'invoice'; pdf.rect(0, 0, 612, 110).fill('#172033'); pdf.fillColor('#f59e0b').fontSize(11).font('Helvetica-Bold').text('MARKETDIRECT.CO.ZA', 42, 34); pdf.fillColor('#fff').fontSize(25).text(invoice ? 'PAID INVOICE' : 'QUOTE', 42, 54); pdf.fontSize(10).text(document.document_number, 420, 65, { width: 145, align: 'right' }); pdf.fillColor('#172033').font('Helvetica').fontSize(10).text(`From\n${supplier.legalName}\n${supplier.address}\n${supplier.email} · VAT ${supplier.vatNumber}`, 42, 140, { lineGap: 4 }); pdf.text(`To\n${customer.companyName || customer.name}\n${customer.name || ''}\n${customer.email || ''}\n${customer.phone || ''}`, 330, 140, { lineGap: 4 }); pdf.moveTo(42, 245).lineTo(570, 245).stroke('#e2e8f0'); pdf.fillColor('#64748b').fontSize(9).text('DESCRIPTION', 42, 260); pdf.text('AMOUNT', 450, 260, { width: 120, align: 'right' }); pdf.fillColor('#172033').fontSize(12).text(line.description || 'EstateWatch subscription', 42, 282, { width: 380 }); pdf.text(money(document.total_cents), 450, 282, { width: 120, align: 'right' }); pdf.fillColor('#64748b').fontSize(10).text(`Issue date: ${new Date(document.issue_date).toLocaleDateString('en-ZA')}\n${document.validity_date ? `Valid until: ${new Date(document.validity_date).toLocaleDateString('en-ZA')}` : ''}\nStatus: ${document.status}`, 42, 350, { lineGap: 5 }); pdf.text(`Subtotal excl. VAT  ${money(document.taxable_total_cents)}\nVAT 15%  ${money(document.vat_cents)}\nTOTAL  ${money(document.total_cents)}`, 375, 350, { width: 195, align: 'right', lineGap: 6 }); pdf.roundedRect(42, 450, 528, 100, 8).fill('#f8fafc'); pdf.fillColor('#172033').fontSize(11).font('Helvetica-Bold').text('Payment details', 58, 470); pdf.font('Helvetica').fontSize(9).text(`Bank: ${BANK_PAYMENT_DETAILS.bank}\nAccount holder: ${BANK_PAYMENT_DETAILS.accountHolder}\nAccount: ${BANK_PAYMENT_DETAILS.accountNumber} · Branch: ${BANK_PAYMENT_DETAILS.branchCode}\nReference: ${document.document_number}`, 58, 490, { lineGap: 4 }); pdf.fillColor('#64748b').fontSize(9).text(invoice ? 'Payment received. Thank you for choosing EstateWatch.' : 'Payment due before activation. This quote is valid for 14 days.', 42, 590); pdf.text('Generated securely by MarketDirect.co.za', 42, 770); pdf.end(); }); }

export function billingDocumentHtml(document: any, baseUrl: string) { const customer = document.customer_snapshot || {}; const line = (document.line_items || [])[0] || {}; const invoice = document.type === 'invoice'; return `<!doctype html><html><body style="margin:0;background:#f4f6f8;font-family:Arial;color:#172033"><main style="max-width:780px;margin:28px auto;background:#fff"><header style="background:#172033;padding:32px;color:white;border-top:7px solid ${invoice ? '#df3348' : '#0b67c2'}"><div style="color:#f59e0b;font-weight:bold;letter-spacing:1px">MARKETDIRECT.CO.ZA</div><h1 style="margin:10px 0 4px">${invoice ? 'Paid Invoice' : 'Quote'}</h1><strong>${esc(document.document_number)}</strong></header><section style="padding:32px;display:flex;justify-content:space-between;gap:40px"><div><b>From</b><p>${esc(supplier.legalName)}<br>${esc(supplier.address)}<br>${esc(supplier.email)}<br>VAT ${esc(supplier.vatNumber)}</p></div><div><b>To</b><p>${esc(customer.companyName || customer.name)}<br>${esc(customer.name || '')}<br>${esc(customer.email || '')}<br>${esc(customer.phone || '')}</p></div></section><section style="padding:0 32px"><table style="width:100%;border-collapse:collapse"><thead><tr style="background:#172033;color:#fff;text-align:left"><th style="padding:14px">Description</th><th style="padding:14px;text-align:right">Amount</th></tr></thead><tbody><tr><td style="padding:18px 14px;border-bottom:1px solid #e2e8f0">${esc(line.description || 'EstateWatch subscription')}</td><td style="padding:18px 14px;text-align:right;border-bottom:1px solid #e2e8f0">${money(document.total_cents)}</td></tr></tbody></table><p style="text-align:right;line-height:2">Subtotal excl. VAT: ${money(document.taxable_total_cents)}<br>VAT 15%: ${money(document.vat_cents)}<br><strong style="font-size:20px">Total: ${money(document.total_cents)}</strong></p></section><section style="margin:32px;padding:20px;background:#f8fafc"><b>Payment details</b><p>Bank: ${esc(BANK_PAYMENT_DETAILS.bank)}<br>Account holder: ${esc(BANK_PAYMENT_DETAILS.accountHolder)}<br>Account: ${esc(BANK_PAYMENT_DETAILS.accountNumber)} · Branch: ${esc(BANK_PAYMENT_DETAILS.branchCode)}<br>Reference: ${esc(document.document_number)}</p></section><footer style="background:#172033;color:#d8dee8;padding:18px 32px;font-size:12px">${invoice ? 'Payment received.' : 'Payment due before activation. Quote valid for 14 days.'} · <a style="color:#f59e0b" href="${esc(baseUrl)}">Open in EstateWatch</a></footer></main></body></html>`; }
