import crypto from 'node:crypto';
export type PaymentFields = Record<string, string | number | undefined | null>;
const order = ['merchant_id','merchant_key','return_url','cancel_url','notify_url','name_first','name_last','email_address','cell_number','m_payment_id','amount','item_name','item_description','custom_int1','custom_int2','custom_int3','custom_int4','custom_int5','custom_str1','custom_str2','custom_str3','custom_str4','custom_str5','email_confirmation','confirmation_address','payment_method','subscription_type','billing_date','recurring_amount','frequency','cycles','pf_payment_id','payment_status','amount_gross','amount_fee','amount_net'];
const index = new Map(order.map((key, position) => [key, position]));
const encode = (value: string) => encodeURIComponent(value).replace(/%20/g, '+');
export const PAYFAST_MERCHANT_ID = process.env.PAYFAST_MERCHANT_ID || '10000100';
export const PAYFAST_MERCHANT_KEY = process.env.PAYFAST_MERCHANT_KEY || '46f0cd694581a';
export const BANK_PAYMENT_DETAILS = { bank: process.env.BANK_NAME || 'CAPITEC', accountHolder: process.env.BANK_ACCOUNT_HOLDER || 'MR BONGANI MANJANJA', businessName: process.env.BANK_BUSINESS_NAME || 'Numedia Direct Marketing', accountType: process.env.BANK_ACCOUNT_TYPE || 'Entrepreneur Account', accountNumber: process.env.BANK_ACCOUNT_NUMBER || '2485902700', branchCode: process.env.BANK_BRANCH_CODE || '470010', proofEmail: process.env.BANK_PROOF_EMAIL || 'accounts@marketdirect.co.za' };
export const PLAN_PRICES_CENTS: Record<string, Record<string, number>> = { pro: { monthly: 69900, annual: 587200 }, agency: { monthly: 249900, annual: 2099200 } };
export const FREE_TIER_LIMITS = { savedAlerts: 1, estateViewsPerMonth: 10, pipelineOpportunities: 3 } as const;
export function buildSignature(fields: PaymentFields, passphrase = process.env.PAYFAST_PASSPHRASE || '') { const pairs = Object.entries(fields).filter(([key,value])=>key!=='signature'&&value!==undefined&&value!==null&&String(value).trim()!=='').sort(([a],[b])=>(index.get(a)??Number.MAX_SAFE_INTEGER)-(index.get(b)??Number.MAX_SAFE_INTEGER)||a.localeCompare(b)).map(([key,value])=>`${key}=${encode(String(value).trim())}`); if(passphrase)pairs.push(`passphrase=${encode(passphrase.trim())}`); return crypto.createHash('md5').update(pairs.join('&')).digest('hex'); }
export function verifySignature(fields: PaymentFields) { const provided=String(fields.signature||'').toLowerCase(), expected=buildSignature(fields).toLowerCase(); return provided.length===expected.length&&crypto.timingSafeEqual(Buffer.from(provided),Buffer.from(expected)); }
export function payfastEndpoint() { return process.env.PAYFAST_SANDBOX==='false'?'https://www.payfast.co.za/eng/process':'https://sandbox.payfast.co.za/eng/process'; }
export function createCheckoutFields(input:{reference:string;amountCents:number;planName:string;email:string;baseUrl:string}) { const fields={merchant_id:PAYFAST_MERCHANT_ID,merchant_key:PAYFAST_MERCHANT_KEY,return_url:`${input.baseUrl}/?payment=success`,cancel_url:`${input.baseUrl}/?payment=cancelled`,notify_url:`${input.baseUrl}/api/payfast/itn`,m_payment_id:input.reference,amount:(input.amountCents/100).toFixed(2),item_name:`EstateWatch ${input.planName}`.slice(0,100),email_address:input.email}; return {...fields,signature:buildSignature(fields)}; }
