import React, { useEffect, useState } from 'react';
import { ClipboardList, RefreshCw, ShieldCheck } from 'lucide-react';
import { AdminSubscriptionUser, AuditEvent, fetchAdminAudit, fetchAdminSubscriptions, updateAdminSubscription } from '../services/api';

export const AdminEntitlementsView: React.FC = () => {
  const [users,setUsers]=useState<AdminSubscriptionUser[]>([]); const [audit,setAudit]=useState<AuditEvent[]>([]); const [error,setError]=useState('');
  const load=async()=>{setError(''); const [u,a]=await Promise.all([fetchAdminSubscriptions(),fetchAdminAudit()]); if(!u||!a)setError('Account controls could not be loaded.'); else {setUsers(u);setAudit(a);}};
  useEffect(()=>{void load();},[]);
  const change=async(user:AdminSubscriptionUser)=>{const next=user.subscriptionStatus==='active'?'inactive':'active'; if(!await updateAdminSubscription(user.id,next)){setError('Subscription status was not saved.');return;} setUsers(current=>current.map(item=>item.id===user.id?{...item,subscriptionStatus:next}:item)); void load();};
  const expire=async(user:AdminSubscriptionUser)=>{if(!await updateAdminSubscription(user.id,'inactive',new Date().toISOString()))setError('Subscription expiry was not saved.'); else void load();};
  return <div className="space-y-5">
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold text-white text-sm flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-amber-400" />Subscription entitlements</h2><p className="text-xs text-slate-400 mt-1">Admin-managed access. Activating an account resumes its paused alerts; deactivating or expiring it pauses delivery.</p></div><button onClick={()=>void load()} className="p-2 rounded-lg bg-slate-800 text-slate-300"><RefreshCw className="w-4 h-4" /></button></div>{error&&<p className="text-xs text-rose-400 mt-3">{error}</p>}<div className="overflow-x-auto mt-4"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-slate-500 border-b border-slate-800"><tr><th className="p-2">Account</th><th className="p-2">Mobile</th><th className="p-2">Status</th><th className="p-2">Action</th></tr></thead><tbody className="divide-y divide-slate-800">{users.map(user=><tr key={user.id}><td className="p-2 text-slate-200">{user.name||'Unnamed'}<div className="text-[10px] text-slate-500">{user.email}</div></td><td className="p-2 text-slate-400">{user.phoneMasked||'Not captured'} {user.phoneVerified&&<span className="text-emerald-400">verified</span>}</td><td className="p-2"><span className={user.subscriptionStatus==='active'?'text-emerald-400':'text-amber-400'}>{user.subscriptionStatus}</span></td><td className="p-2 flex gap-1"><button onClick={()=>void change(user)} className="rounded-lg bg-slate-800 px-2 py-1 text-[10px] font-bold text-white">{user.subscriptionStatus==='active'?'Pause':'Activate'}</button><button onClick={()=>void expire(user)} className="rounded-lg bg-rose-950 px-2 py-1 text-[10px] font-bold text-rose-300">Expire</button></td></tr>)}</tbody></table></div></div>
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><h2 className="font-bold text-white text-sm flex items-center gap-2"><ClipboardList className="w-4 h-4 text-amber-400" />Communication & security audit</h2><div className="overflow-x-auto mt-4 max-h-96"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-slate-500 border-b border-slate-800"><tr><th className="p-2">Time</th><th className="p-2">Event</th><th className="p-2">Channel</th><th className="p-2">Status</th><th className="p-2">User</th></tr></thead><tbody className="divide-y divide-slate-800">{audit.map(event=><tr key={event.id}><td className="p-2 text-slate-500 whitespace-nowrap">{event.created_at}</td><td className="p-2 text-slate-200">{event.event_type}</td><td className="p-2 text-slate-400">{event.channel||'—'}</td><td className="p-2 text-slate-400">{event.status||'—'}</td><td className="p-2 text-slate-500">{event.actor_email||event.user_id||'system'}</td></tr>)}</tbody></table></div></div>
  </div>;
};
