import React, { useEffect, useMemo, useState } from 'react';
import { Check, CreditCard, FileText, ShieldCheck } from 'lucide-react';
import { BrandName } from './BrandName';
import { billingDocumentPdfUrl, BillingCycle, BillingPlan, fetchBillingDocuments, fetchBillingEntitlement, fetchBillingPayments, requestBillingQuote, startBillingCheckout } from '../services/api';

type Selection={plan:BillingPlan; cycle:BillingCycle};
const price=(plan:BillingPlan,cycle:BillingCycle)=>plan==='pro'?(cycle==='annual'?5872:699):(cycle==='annual'?20992:2499);
const money=(n:number)=>`R ${n.toLocaleString('en-ZA',{minimumFractionDigits:2})}`;
export const BillingView:React.FC<{isAdmin?:boolean;isSignedIn?:boolean;subscriptionActive?:boolean;subscriptionStatus?:string;subscriptionExpiresAt?:string|null;selection?:Selection;onSelectionChange?:(s:Selection)=>void;onRequestSignIn?:(s:Selection)=>void}> = ({isAdmin=false,isSignedIn=false,subscriptionActive=false,subscriptionStatus='inactive',subscriptionExpiresAt,selection={plan:'pro',cycle:'annual'},onSelectionChange,onRequestSignIn}) => {
  const [docs,setDocs]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[entitlement,setEntitlement]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[quote,setQuote]=useState({contactName:'',companyName:'',vatNumber:''}),[method,setMethod]=useState<'payfast'|'bank_transfer'>('payfast'),[bank,setBank]=useState<any>(null);
  const setSelection=(s:Selection)=>onSelectionChange?.(s); const selected=selection;
  useEffect(()=>{ if(!isSignedIn||isAdmin)return; let alive=true; Promise.all([fetchBillingEntitlement(),fetchBillingDocuments(),fetchBillingPayments()]).then(([e,d,p])=>{if(alive){setEntitlement(e);setDocs(d);setPayments(p)}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setBusy(false)); return()=>{alive=false}; },[isSignedIn,isAdmin]);
  const choose=(plan:BillingPlan)=>{const next={plan,cycle:selected.cycle};setSelection(next); if(!isSignedIn)onRequestSignIn?.(next);};
  const quoteSubmit=async()=>{try{setBusy(true);setError('');const result=await requestBillingQuote({plan:selected.plan,billingCycle:selected.cycle,...quote});setDocs(d=>[result.document,...d]);}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const pay=async(quoteId?:string)=>{try{setBusy(true);setError('');const result=await startBillingCheckout({plan:selected.plan,billingCycle:selected.cycle,method,quoteId});if(method==='bank_transfer')setBank(result);else{const form=document.createElement('form');form.method='POST';form.action=result.checkout.endpoint;Object.entries(result.checkout.fields).forEach(([k,v])=>{const input=document.createElement('input');input.type='hidden';input.name=k;input.value=String(v);form.appendChild(input)});document.body.appendChild(form);form.submit();}}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const plans=useMemo(()=>[{key:'pro' as BillingPlan,name:'Pro Solo',desc:'For solo estate attorneys, investors and tracers',accent:'amber'},{key:'agency' as BillingPlan,name:'Agency / Firm',desc:'For law firms, agencies and investor teams',accent:'purple'}],[ ]);
  return <div className="space-y-6">
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="flex items-center gap-2 text-lg font-bold text-white"><CreditCard className="h-5 w-5 text-amber-400"/>Subscription & plans</h2><p className="mt-1 text-xs text-slate-400">Choose annual billing for the best value. Quotes and payment actions are protected inside your account.</p></div><div className="flex rounded-xl border border-slate-700 bg-slate-950 p-1 text-xs"><button onClick={()=>setSelection({plan:selected.plan,cycle:'monthly'})} className={`rounded-lg px-3 py-2 font-bold ${selected.cycle==='monthly'?'bg-amber-500 text-slate-950':'text-slate-400'}`}>Monthly</button><button onClick={()=>setSelection({plan:selected.plan,cycle:'annual'})} className={`rounded-lg px-3 py-2 font-bold ${selected.cycle==='annual'?'bg-amber-500 text-slate-950':'text-slate-400'}`}>Annual <span className="ml-1 rounded bg-emerald-400 px-1 text-[9px] text-slate-950">SAVE 30%</span></button></div></div></section>
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><span className="text-xs font-bold uppercase tracking-wider text-emerald-400">Free tier</span><h3 className="mt-2 text-2xl font-extrabold text-white">R 0</h3><p className="mt-1 text-xs text-slate-400">A practical starting point for every signed-in user.</p><ul className="mt-4 space-y-2 text-xs text-slate-300"><li><Check className="mr-2 inline h-3.5 w-3.5 text-emerald-400"/>1 saved alert</li><li><Check className="mr-2 inline h-3.5 w-3.5 text-emerald-400"/>10 estate views per month</li><li><Check className="mr-2 inline h-3.5 w-3.5 text-emerald-400"/>3 saved opportunities</li><li className="text-slate-500">No automated alert delivery</li><li>Original official Gazette PDF for signed-in users</li></ul><p className="mt-4 text-[11px] text-slate-500">Source documents are official public Government Gazette material.</p></div>{plans.map(p=><div key={p.key} className={`rounded-2xl border-2 ${selected.plan===p.key?'border-amber-400':'border-slate-700'} bg-slate-900 p-5`}><span className="text-xs font-bold uppercase tracking-wider text-amber-400">{p.name}</span><h3 className="mt-2 text-2xl font-extrabold text-white">{money(price(p.key,selected.cycle))}<span className="text-xs font-normal text-slate-400"> / {selected.cycle==='annual'?'year':'month'}</span></h3>{selected.cycle==='annual'&&<p className="mt-1 text-xs font-bold text-emerald-400">Save 30% with annual billing · {money(Math.round(price(p.key,'annual')/12))} monthly equivalent</p>}<p className="mt-2 text-xs text-slate-400">{p.desc}</p><ul className="mt-4 space-y-2 text-xs text-slate-300"><li><Check className="mr-2 inline h-3.5 w-3.5 text-amber-400"/>Expanded alert delivery</li><li><Check className="mr-2 inline h-3.5 w-3.5 text-amber-400"/>Full workflow and document access</li><li><Check className="mr-2 inline h-3.5 w-3.5 text-amber-400"/>Priority account support</li></ul><button onClick={()=>choose(p.key)} className="mt-5 w-full rounded-xl bg-amber-500 py-3 text-xs font-extrabold text-slate-950 hover:bg-amber-400">{isSignedIn?'Choose plan':'Sign in to continue'}</button></div>)}</section>
    {!isSignedIn&&!isAdmin&&<section className="rounded-2xl border border-blue-500/30 bg-blue-950/20 p-5"><p className="text-sm font-bold text-white">Sign in to request a quote or pay</p><p className="mt-1 text-xs text-slate-300">Your selected plan and annual/monthly choice will be kept when you sign in.</p><button onClick={()=>onRequestSignIn?.(selected)} className="mt-4 rounded-xl bg-blue-500 px-4 py-2 text-xs font-bold text-white">Sign in to request a quote</button></section>}
    {!isSignedIn&&!isAdmin&&<section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-bold text-white">Billing history</h3><p className="mt-2 text-xs leading-relaxed text-slate-400">Quotes, invoices and payment history are available after you sign in. This keeps your financial records private and lets us show only documents belonging to your account.</p><button onClick={()=>onRequestSignIn?.(selected)} className="mt-4 rounded-xl border border-slate-700 bg-slate-950 px-4 py-2 text-xs font-bold text-slate-200 hover:border-amber-400 hover:text-amber-300">Sign in to view billing history</button></section>}
    {isAdmin&&<section className="rounded-2xl border border-amber-500/40 bg-slate-900 p-6"><div className="flex items-center gap-3 text-xl font-bold text-amber-300"><ShieldCheck className="h-7 w-7"/>Administrator access</div><p className="mt-3 text-sm text-slate-300">All <BrandName/> functionality is enabled. Subscription limits do not apply.</p></section>}
    {isSignedIn&&!isAdmin&&<><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold text-white">Your access</h3><p className="mt-1 text-xs text-slate-400">{subscriptionActive?'Paid access active':'Free tier'} · {subscriptionExpiresAt?`until ${new Date(subscriptionExpiresAt).toLocaleDateString('en-ZA')}`:'no expiry'}</p></div><span className="rounded-full bg-emerald-950 px-3 py-1 text-xs font-bold text-emerald-400">{entitlement?.status||subscriptionStatus}</span></div>{entitlement?.usage&&<p className="mt-4 text-xs text-slate-300">Free-tier usage: {entitlement.usage.estateViews}/10 estate views · {entitlement.usage.savedAlerts}/1 saved alert · {entitlement.usage.pipelineOpportunities}/3 opportunities</p>}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="flex items-center gap-2 font-bold text-white"><FileText className="h-4 w-4 text-amber-400"/>Request a quote</h3><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={quote.contactName} onChange={e=>setQuote({...quote,contactName:e.target.value})} placeholder="Contact name" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white"/><input value={quote.companyName} onChange={e=>setQuote({...quote,companyName:e.target.value})} placeholder="Company name" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white"/><input value={quote.vatNumber} onChange={e=>setQuote({...quote,vatNumber:e.target.value})} placeholder="VAT number (optional)" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white"/></div><button disabled={busy} onClick={()=>void quoteSubmit()} className="mt-4 rounded-xl bg-blue-500 px-5 py-3 text-xs font-bold text-white">{busy?'Preparing…':'Create and email quote'}</button></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-bold text-white">Pay securely</h3><p className="mt-1 text-xs text-slate-400">{money(price(selected.plan,selected.cycle))} before VAT · {selected.plan} · {selected.cycle}</p><div className="mt-4 flex gap-2"><button onClick={()=>setMethod('payfast')} className={`rounded-lg px-3 py-2 text-xs font-bold ${method==='payfast'?'bg-blue-500 text-white':'bg-slate-800 text-slate-300'}`}>PayFast</button><button onClick={()=>setMethod('bank_transfer')} className={`rounded-lg px-3 py-2 text-xs font-bold ${method==='bank_transfer'?'bg-amber-500 text-slate-950':'bg-slate-800 text-slate-300'}`}>Bank transfer</button></div><button disabled={busy} onClick={()=>void pay()} className="mt-4 w-full rounded-xl bg-emerald-500 py-3 text-sm font-extrabold text-slate-950">{method==='bank_transfer'?'Create bank payment':'Continue to PayFast'}</button>{bank&&<div className="mt-4 rounded-xl border border-amber-500/30 bg-amber-950/20 p-4 text-xs text-slate-200">{bank.message}<br/>Reference: <strong>{bank.payment.reference}</strong><br/>{bank.bankDetails.bank} · {bank.bankDetails.accountNumber} · Branch {bank.bankDetails.branchCode}</div>}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-bold text-white">Your quotes and invoices</h3>{docs.length===0?<p className="mt-3 text-xs text-slate-500">Your documents will appear here after you request a quote or complete payment.</p>:<div className="mt-3 space-y-2">{docs.map(d=><div key={d.id} className="flex flex-col gap-2 rounded-xl bg-slate-950 p-3 text-xs md:flex-row md:items-center md:justify-between"><span className="text-slate-200">{d.type==='invoice'?'Invoice':'Quote'} {d.document_number}</span><span className="text-amber-300">{d.type==='invoice'?'Paid':d.status==='sent'?'Ready to pay':d.status}</span><a href={billingDocumentPdfUrl(d.id)} target="_blank" rel="noreferrer" className="font-bold text-blue-400">View / download</a></div>)}</div>}</section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-bold text-white">Payment history</h3>{payments.length===0?<p className="mt-3 text-xs text-slate-500">No payments yet.</p>:<div className="mt-3 space-y-2">{payments.map(p=><div key={p.id} className="flex justify-between rounded-xl bg-slate-950 p-3 text-xs"><span className="text-slate-300">{p.reference}</span><span className="text-slate-200">{p.status==='awaiting_review'?'Awaiting bank review':p.status}</span></div>)}</div>}</section></>}
    {error&&<p role="alert" className="rounded-xl border border-rose-500/30 bg-rose-950/20 p-3 text-xs text-rose-300">{error}</p>}
  </div>;
};
